### ISSUE TITLE
please add to racket package catalog

### ISSUE THREAD

**Issue by spdegabrielle** [mcdejonge/rs#2]
https://pkgs.racket-lang.org/index.html

**Comment by spdegabrielle** [comment]
Sorry - I got excited. While making this available as a package will make it easier for others to use it, this code isn't set up as a package, so it can't be added as package to racket package catalog.

I think it would be good to make your code available as a package, as it would allow other users to build upon it. Maybe a gui interface, or use it in a game. 

[Making a package](https://blog.racket-lang.org/2017/10/tutorial-creating-a-package.html) is fairly easy, but your code has dependencies. There are two options; 
1) make use of the existing documentation and require users to install RtMidi manually
2) package the RtMidi libraries in the package.

I think the first option is a good start. If you are interested I would be happy to make a rough first draft of a package as a PR.
Kind regards

**Comment by mcdejonge** [comment]
Hi spdegabrielle,

Technically creating a Racket package would be no problem - just RTFM and get it done - but it will not make it easier for others to use this as:

1. It’s dependent on RtMidi. This in itself is not a problem but:

2. RtMidi requires manually downloading and compiling code inside the installed package directory.

AND

3. RtMidi does not work without hacking the code.

I have made a pull request to solve #3 but it’s a 6 year old project so it might be a while before it gets accepted. And I would prefer not to fork RtMidi for such a small issue.

#2 is a bigger problem. Do you know how other ffi using libraries deal with this? 

Making it plug an play is highly desirable, yes, but I think this should only be done if it truly *is* plug and play - which at the moment it is not. Though I would love to make it such, of course. It’s just that I’m too much of a Racket noob to know how to go about achieving this.

**Comment by mcdejonge** [comment]
Hi @spdegabrielle 

Unfortunately, after nearly two weeks I haven't received a response to my pull request for John Clements' RtMidi wrapper library. I'm guessing that means it's dead.

Writing one myself is beyond my current abilities (and, to be honest, interests). So I guess that leaves the unpleasant option of turning the current code into a package and supply it with a manual that tells users they need to install another package, hack it *and* compile yet another bit of software.

Unless you have a better idea?

**Comment by spdegabrielle** [comment]
Hi @mcdejonge 
Please be patient - @jbclements is a working professor and this is the busiest time of the year for university lecturers.

I’m happy to help you with the turning it into a package.  There is a nice tutorial. https://blog.racket-lang.org/2017/10/tutorial-creating-a-package.html
Best regards 
Stephen

**Comment by jbclements** [comment]
Yikes! Many thanks for the bump. I'll take a quick 15-minute look at this.

**Comment by jbclements** [comment]
My fifteen minutes are up, sigh. I'm going to put comments on the pull request there, rather than in this thread, here.

**Comment by mcdejonge** [comment]
@spdegabrielle it turns out the RTMidi wrapper is still alive :-)

I'll turn rs into a package and work with  @jbclements  to fix the small bug I found in it.

Thanks for your guidance and help so far.

**Comment by mcdejonge** [comment]
Done.

See https://pkgd.racket-lang.org/pkgn/package/rs

I've separated out the demos: https://github.com/mcdejonge/rs-demos

Next up: write some documentation in Scribble.
